export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CartActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM: "CLEAR_ITEM"
};

export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER"
};

export const ShopActionTypes = {
  UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS",
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAIL: "FETCH_COLLECTIONS_FAIL"
};
